// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserActivityLog.Data;

namespace UserActivityLog.Migrations
{
    [DbContext(typeof(UserActivityLogContext))]
    partial class UserActivityLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserActivityLog.Models.UserLog", b =>
                {
                    b.Property<long>("ulogo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("http_verb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("login_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("login_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("page_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ulogo_id");

                    b.ToTable("UserLog");
                });
#pragma warning restore 612, 618
        }
    }
}
